workflows:
  workflows/pr_checks.yml:
    jobs:
      danger:
        strategy:
          matrix:
            xcode: latest
      pod_lib_lint:
        strategy:
          matrix:
            xcode: latest

  workflows/release.yml:
    jobs:
      validate_release:
        strategy:
          matrix:
            xcode: latest
      github_release:
        strategy:
          matrix:
            xcode: latest
      build_docs:
        strategy:
          matrix:
            xcode: latest

  workflows/tests.yml:
    jobs:
      swiftpm_tests:
        strategy:
          matrix:
            xcode:
              - latest
              - latest-beta
      xcode_tests:
        strategy:
          matrix:
            xcode:
              - latest
              - latest-beta
      carthage_archive:
        strategy:
          matrix:
            xcode: latest
